# Generated by Django 3.2.19 on 2025-04-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_item', models.IntegerField()),
                ('added_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stock_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.categorymaster')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.productmaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('door_no', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.productmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.usermaster')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='reviewmaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.usermaster'),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.usermaster'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ui.ordermaster'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.productmaster'),
        ),
        migrations.AddField(
            model_name='cartmaster',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.productmaster'),
        ),
        migrations.AddField(
            model_name='cartmaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.usermaster'),
        ),
    ]
