# Generated by Django 3.2.19 on 2025-04-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20250411_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
