# Generated by Django 3.2.19 on 2025-04-12 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_auto_20250412_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmaster',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartmaster',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cartmaster',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='cartmaster',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='cartmaster',
            name='no_of_item',
        ),
    ]
