# Generated by Django 3.2.19 on 2025-04-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20250412_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='area',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='usermaster',
            old_name='postal_code',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='door_no',
        ),
        migrations.AddField(
            model_name='usermaster',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
