# Generated by Django 4.2.20 on 2025-04-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0010_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermaster",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ordermaster",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ordermaster",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
