# Generated by Django 4.2.20 on 2025-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0011_ordermaster_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymaster",
            name="category_description",
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="category_image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/", default=None),
        ),
    ]
