# Generated by Django 4.2.20 on 2025-07-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0012_categorymaster_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymaster",
            name="category_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="categorymaster",
            name="category_image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
    ]
